package com.rank.ccms.entities;
// Generated 24 Apr, 2018 12:53:14 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "MyBms")
public class Address implements java.io.Serializable {

	private int id;
	private Country country;
	private String type;
	private String line1;
	private String line2;
	private String suburbDistrict;
	private Integer cityId;
	private Integer stateId;
	private String postCode;
	private String latitude;
	private String longitude;
	private Set<BusinessSettings> businessSettingses = new HashSet<BusinessSettings>(0);
	private Set<Jobs> jobsesForFromAddressId = new HashSet<Jobs>(0);
	private Set<Jobs> jobsesForToAddressId = new HashSet<Jobs>(0);

	public Address() {
	}

	public Address(int id) {
		this.id = id;
	}

	public Address(int id, Country country, String type, String line1, String line2, String suburbDistrict,
			Integer cityId, Integer stateId, String postCode, String latitude, String longitude,
			Set<BusinessSettings> businessSettingses, Set<Jobs> jobsesForFromAddressId,
			Set<Jobs> jobsesForToAddressId) {
		this.id = id;
		this.country = country;
		this.type = type;
		this.line1 = line1;
		this.line2 = line2;
		this.suburbDistrict = suburbDistrict;
		this.cityId = cityId;
		this.stateId = stateId;
		this.postCode = postCode;
		this.latitude = latitude;
		this.longitude = longitude;
		this.businessSettingses = businessSettingses;
		this.jobsesForFromAddressId = jobsesForFromAddressId;
		this.jobsesForToAddressId = jobsesForToAddressId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id")
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "line_1", length = 45)
	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	@Column(name = "line_2", length = 45)
	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	@Column(name = "suburb_district", length = 45)
	public String getSuburbDistrict() {
		return this.suburbDistrict;
	}

	public void setSuburbDistrict(String suburbDistrict) {
		this.suburbDistrict = suburbDistrict;
	}

	@Column(name = "city_id")
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "state_id")
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "post_code", length = 45)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Column(name = "latitude", length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<BusinessSettings> getBusinessSettingses() {
		return this.businessSettingses;
	}

	public void setBusinessSettingses(Set<BusinessSettings> businessSettingses) {
		this.businessSettingses = businessSettingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressByFromAddressId")
	public Set<Jobs> getJobsesForFromAddressId() {
		return this.jobsesForFromAddressId;
	}

	public void setJobsesForFromAddressId(Set<Jobs> jobsesForFromAddressId) {
		this.jobsesForFromAddressId = jobsesForFromAddressId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressByToAddressId")
	public Set<Jobs> getJobsesForToAddressId() {
		return this.jobsesForToAddressId;
	}

	public void setJobsesForToAddressId(Set<Jobs> jobsesForToAddressId) {
		this.jobsesForToAddressId = jobsesForToAddressId;
	}

}
