package com.rank.ccms.entities;
// Generated 23 May, 2018 11:11:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BankMst generated by hbm2java
 */
@Entity
@Table(name = "bank_mst", catalog = "Bms")
public class BankMst implements java.io.Serializable {

	private Integer id;
	private String bankName;
	private String accountName;
	private String accountNumber;
	private String type;
	private Set<BusinessSettings> businessSettingses = new HashSet<BusinessSettings>(0);
	private Set<DriverMst> driverMsts = new HashSet<DriverMst>(0);

	public BankMst() {
	}

	public BankMst(String bankName, String accountName, String accountNumber, String type,
			Set<BusinessSettings> businessSettingses, Set<DriverMst> driverMsts) {
		this.bankName = bankName;
		this.accountName = accountName;
		this.accountNumber = accountNumber;
		this.type = type;
		this.businessSettingses = businessSettingses;
		this.driverMsts = driverMsts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bank_name", length = 45)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "account_name", length = 45)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "account_number", length = 45)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bankMst")
	public Set<BusinessSettings> getBusinessSettingses() {
		return this.businessSettingses;
	}

	public void setBusinessSettingses(Set<BusinessSettings> businessSettingses) {
		this.businessSettingses = businessSettingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bankMst")
	public Set<DriverMst> getDriverMsts() {
		return this.driverMsts;
	}

	public void setDriverMsts(Set<DriverMst> driverMsts) {
		this.driverMsts = driverMsts;
	}

}
