package com.rank.ccms.entities;
// Generated 24 Apr, 2018 12:53:14 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "MyBms")
public class Booking implements java.io.Serializable {

	private int id;
	private BookingDriver bookingDriver;
	private Customer customer;
	private Jobs jobs;
	private Date createdOn;
	private String bookingType;
	private String notes;
	private String bookingSource;
	private String carType;
	private Integer bookingMadeById;

	public Booking() {
	}

	public Booking(int id) {
		this.id = id;
	}

	public Booking(int id, BookingDriver bookingDriver, Customer customer, Jobs jobs, Date createdOn,
			String bookingType, String notes, String bookingSource, String carType, Integer bookingMadeById) {
		this.id = id;
		this.bookingDriver = bookingDriver;
		this.customer = customer;
		this.jobs = jobs;
		this.createdOn = createdOn;
		this.bookingType = bookingType;
		this.notes = notes;
		this.bookingSource = bookingSource;
		this.carType = carType;
		this.bookingMadeById = bookingMadeById;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "booking_driver_id")
	public BookingDriver getBookingDriver() {
		return this.bookingDriver;
	}

	public void setBookingDriver(BookingDriver bookingDriver) {
		this.bookingDriver = bookingDriver;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobs_id")
	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "booking_type", length = 45)
	public String getBookingType() {
		return this.bookingType;
	}

	public void setBookingType(String bookingType) {
		this.bookingType = bookingType;
	}

	@Column(name = "notes", length = 45)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "booking_source", length = 45)
	public String getBookingSource() {
		return this.bookingSource;
	}

	public void setBookingSource(String bookingSource) {
		this.bookingSource = bookingSource;
	}

	@Column(name = "car_type", length = 45)
	public String getCarType() {
		return this.carType;
	}

	public void setCarType(String carType) {
		this.carType = carType;
	}

	@Column(name = "booking_made_by_id")
	public Integer getBookingMadeById() {
		return this.bookingMadeById;
	}

	public void setBookingMadeById(Integer bookingMadeById) {
		this.bookingMadeById = bookingMadeById;
	}

}
