package com.rank.ccms.entities;
// Generated 23 May, 2018 11:11:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookingDriver generated by hbm2java
 */
@Entity
@Table(name = "booking_driver", catalog = "Bms")
public class BookingDriver implements java.io.Serializable {

	private Integer id;
	private DriverMst driverMst;
	private String driverNotes;
	private String driverPrice;
	private Boolean reminder;
	private Date reminderTime;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public BookingDriver() {
	}

	public BookingDriver(DriverMst driverMst, String driverNotes, String driverPrice, Boolean reminder,
			Date reminderTime, Set<Booking> bookings) {
		this.driverMst = driverMst;
		this.driverNotes = driverNotes;
		this.driverPrice = driverPrice;
		this.reminder = reminder;
		this.reminderTime = reminderTime;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "driver_mst_id")
	public DriverMst getDriverMst() {
		return this.driverMst;
	}

	public void setDriverMst(DriverMst driverMst) {
		this.driverMst = driverMst;
	}

	@Column(name = "driver_notes", length = 45)
	public String getDriverNotes() {
		return this.driverNotes;
	}

	public void setDriverNotes(String driverNotes) {
		this.driverNotes = driverNotes;
	}

	@Column(name = "driver_price", length = 45)
	public String getDriverPrice() {
		return this.driverPrice;
	}

	public void setDriverPrice(String driverPrice) {
		this.driverPrice = driverPrice;
	}

	@Column(name = "reminder")
	public Boolean getReminder() {
		return this.reminder;
	}

	public void setReminder(Boolean reminder) {
		this.reminder = reminder;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "reminder_time", length = 8)
	public Date getReminderTime() {
		return this.reminderTime;
	}

	public void setReminderTime(Date reminderTime) {
		this.reminderTime = reminderTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookingDriver")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
