package com.rank.ccms.entities;
// Generated 24 May, 2018 12:57:27 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusinessPhone generated by hbm2java
 */
@Entity
@Table(name = "business_phone", catalog = "Bms")
public class BusinessPhone implements java.io.Serializable {

	private Integer id;
	private String type;
	private String callingCode;
	private String number;
	private Set<BusinessSettings> businessSettingses = new HashSet<BusinessSettings>(0);

	public BusinessPhone() {
	}

	public BusinessPhone(String type, String callingCode, String number, Set<BusinessSettings> businessSettingses) {
		this.type = type;
		this.callingCode = callingCode;
		this.number = number;
		this.businessSettingses = businessSettingses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "calling_code", length = 45)
	public String getCallingCode() {
		return this.callingCode;
	}

	public void setCallingCode(String callingCode) {
		this.callingCode = callingCode;
	}

	@Column(name = "number", length = 45)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessPhone")
	public Set<BusinessSettings> getBusinessSettingses() {
		return this.businessSettingses;
	}

	public void setBusinessSettingses(Set<BusinessSettings> businessSettingses) {
		this.businessSettingses = businessSettingses;
	}

}
