package com.rank.ccms.entities;
// Generated 24 Apr, 2018 12:53:14 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusinessPhone generated by hbm2java
 */
@Entity
@Table(name = "business_phone", catalog = "MyBms")
public class BusinessPhone implements java.io.Serializable {

	private int id;
	private String type;
	private String callingCode;
	private String number;
	private Set<BusinessSettings> businessSettingses = new HashSet<BusinessSettings>(0);

	public BusinessPhone() {
	}

	public BusinessPhone(int id) {
		this.id = id;
	}

	public BusinessPhone(int id, String type, String callingCode, String number,
			Set<BusinessSettings> businessSettingses) {
		this.id = id;
		this.type = type;
		this.callingCode = callingCode;
		this.number = number;
		this.businessSettingses = businessSettingses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "calling_code", length = 45)
	public String getCallingCode() {
		return this.callingCode;
	}

	public void setCallingCode(String callingCode) {
		this.callingCode = callingCode;
	}

	@Column(name = "number", length = 45)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessPhone")
	public Set<BusinessSettings> getBusinessSettingses() {
		return this.businessSettingses;
	}

	public void setBusinessSettingses(Set<BusinessSettings> businessSettingses) {
		this.businessSettingses = businessSettingses;
	}

}
