package com.rank.ccms.entities;
// Generated 24 May, 2018 12:57:27 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DriverMst generated by hbm2java
 */
@Entity
@Table(name = "driver_mst", catalog = "Bms")
public class DriverMst implements java.io.Serializable {

	private Integer id;
	private BankMst bankMst;
	private Date createdOn;
	private String createdBy;
	private Boolean status;
	private String title;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String userId;
	private String workPhone;
	private String homePhone;
	private String mobile;
	private String notes;
	private Set<Car> cars = new HashSet<Car>(0);
	private Set<BookingDriver> bookingDrivers = new HashSet<BookingDriver>(0);

	public DriverMst() {
	}

	public DriverMst(BankMst bankMst) {
		this.bankMst = bankMst;
	}

	public DriverMst(BankMst bankMst, Date createdOn, String createdBy, Boolean status, String title, String firstName,
			String lastName, String email, String password, String userId, String workPhone, String homePhone,
			String mobile, String notes, Set<Car> cars, Set<BookingDriver> bookingDrivers) {
		this.bankMst = bankMst;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.status = status;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.userId = userId;
		this.workPhone = workPhone;
		this.homePhone = homePhone;
		this.mobile = mobile;
		this.notes = notes;
		this.cars = cars;
		this.bookingDrivers = bookingDrivers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_mst_id", nullable = false)
	public BankMst getBankMst() {
		return this.bankMst;
	}

	public void setBankMst(BankMst bankMst) {
		this.bankMst = bankMst;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "user_id", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "work_phone", length = 45)
	public String getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	@Column(name = "home_phone", length = 45)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "mobile", length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "notes", length = 45)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "driverMst")
	public Set<Car> getCars() {
		return this.cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "driverMst")
	public Set<BookingDriver> getBookingDrivers() {
		return this.bookingDrivers;
	}

	public void setBookingDrivers(Set<BookingDriver> bookingDrivers) {
		this.bookingDrivers = bookingDrivers;
	}

}
