package com.rank.ccms.entities;
// Generated 24 May, 2018 12:57:27 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailDetails generated by hbm2java
 */
@Entity
@Table(name = "email_details", catalog = "Bms")
public class EmailDetails implements java.io.Serializable {

	private Integer id;
	private BusinessSettings businessSettings;
	private String type;
	private String emailId;
	private String smtp;
	private String smtpUsername;
	private String smtpPassword;

	public EmailDetails() {
	}

	public EmailDetails(BusinessSettings businessSettings, String type, String emailId, String smtp,
			String smtpUsername, String smtpPassword) {
		this.businessSettings = businessSettings;
		this.type = type;
		this.emailId = emailId;
		this.smtp = smtp;
		this.smtpUsername = smtpUsername;
		this.smtpPassword = smtpPassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_settings_id")
	public BusinessSettings getBusinessSettings() {
		return this.businessSettings;
	}

	public void setBusinessSettings(BusinessSettings businessSettings) {
		this.businessSettings = businessSettings;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "email_id", length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "smtp", length = 45)
	public String getSmtp() {
		return this.smtp;
	}

	public void setSmtp(String smtp) {
		this.smtp = smtp;
	}

	@Column(name = "smtp_username", length = 45)
	public String getSmtpUsername() {
		return this.smtpUsername;
	}

	public void setSmtpUsername(String smtpUsername) {
		this.smtpUsername = smtpUsername;
	}

	@Column(name = "smtp_password", length = 45)
	public String getSmtpPassword() {
		return this.smtpPassword;
	}

	public void setSmtpPassword(String smtpPassword) {
		this.smtpPassword = smtpPassword;
	}

}
