package com.rank.ccms.entities;
// Generated 24 May, 2018 12:57:27 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExtraPrices generated by hbm2java
 */
@Entity
@Table(name = "extra_prices", catalog = "Bms")
public class ExtraPrices implements java.io.Serializable {

	private Integer id;
	private String extrasTypeId;
	private String extraPrice;
	private Set<JobFare> jobFares = new HashSet<JobFare>(0);

	public ExtraPrices() {
	}

	public ExtraPrices(String extrasTypeId, String extraPrice, Set<JobFare> jobFares) {
		this.extrasTypeId = extrasTypeId;
		this.extraPrice = extraPrice;
		this.jobFares = jobFares;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "extras_type_id", length = 45)
	public String getExtrasTypeId() {
		return this.extrasTypeId;
	}

	public void setExtrasTypeId(String extrasTypeId) {
		this.extrasTypeId = extrasTypeId;
	}

	@Column(name = "extra_price", length = 45)
	public String getExtraPrice() {
		return this.extraPrice;
	}

	public void setExtraPrice(String extraPrice) {
		this.extraPrice = extraPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extraPrices")
	public Set<JobFare> getJobFares() {
		return this.jobFares;
	}

	public void setJobFares(Set<JobFare> jobFares) {
		this.jobFares = jobFares;
	}

}
