package com.rank.ccms.entities;
// Generated 24 May, 2018 12:57:27 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExtraMst generated by hbm2java
 */
@Entity
@Table(name = "extra_mst", catalog = "Bms")
public class ExtraMst implements java.io.Serializable {

	private Integer id;
	private Jobs jobs;
	private String extraTypeId;
	private String extraYesNo;
	private String extraNos;
	private String extraPrice;

	public ExtraMst() {
	}

	public ExtraMst(Jobs jobs, String extraTypeId, String extraYesNo, String extraNos, String extraPrice) {
		this.jobs = jobs;
		this.extraTypeId = extraTypeId;
		this.extraYesNo = extraYesNo;
		this.extraNos = extraNos;
		this.extraPrice = extraPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobs_id")
	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	@Column(name = "extra_type_id", length = 45)
	public String getExtraTypeId() {
		return this.extraTypeId;
	}

	public void setExtraTypeId(String extraTypeId) {
		this.extraTypeId = extraTypeId;
	}

	@Column(name = "extra_yes_no", length = 45)
	public String getExtraYesNo() {
		return this.extraYesNo;
	}

	public void setExtraYesNo(String extraYesNo) {
		this.extraYesNo = extraYesNo;
	}

	@Column(name = "extra_nos", length = 45)
	public String getExtraNos() {
		return this.extraNos;
	}

	public void setExtraNos(String extraNos) {
		this.extraNos = extraNos;
	}

	@Column(name = "extra_price", length = 45)
	public String getExtraPrice() {
		return this.extraPrice;
	}

	public void setExtraPrice(String extraPrice) {
		this.extraPrice = extraPrice;
	}

}
