package com.rank.ccms.entities;
// Generated 24 Apr, 2018 12:53:14 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExtraPrices generated by hbm2java
 */
@Entity
@Table(name = "extra_prices", catalog = "MyBms")
public class ExtraPrices implements java.io.Serializable {

	private int id;
	private String extrasTypeId;
	private String extraPrice;
	private Set<JobFare> jobFares = new HashSet<JobFare>(0);

	public ExtraPrices() {
	}

	public ExtraPrices(int id) {
		this.id = id;
	}

	public ExtraPrices(int id, String extrasTypeId, String extraPrice, Set<JobFare> jobFares) {
		this.id = id;
		this.extrasTypeId = extrasTypeId;
		this.extraPrice = extraPrice;
		this.jobFares = jobFares;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "extras_type_id", length = 45)
	public String getExtrasTypeId() {
		return this.extrasTypeId;
	}

	public void setExtrasTypeId(String extrasTypeId) {
		this.extrasTypeId = extrasTypeId;
	}

	@Column(name = "extra_price", length = 45)
	public String getExtraPrice() {
		return this.extraPrice;
	}

	public void setExtraPrice(String extraPrice) {
		this.extraPrice = extraPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extraPrices")
	public Set<JobFare> getJobFares() {
		return this.jobFares;
	}

	public void setJobFares(Set<JobFare> jobFares) {
		this.jobFares = jobFares;
	}

}
