package com.rank.ccms.entities;
// Generated 23 May, 2018 11:11:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobFare generated by hbm2java
 */
@Entity
@Table(name = "job_fare", catalog = "Bms")
public class JobFare implements java.io.Serializable {

	private Integer id;
	private ExtraPrices extraPrices;
	private String basePrice;
	private String totalFare;
	private Set<Jobs> jobses = new HashSet<Jobs>(0);

	public JobFare() {
	}

	public JobFare(ExtraPrices extraPrices, String basePrice, String totalFare, Set<Jobs> jobses) {
		this.extraPrices = extraPrices;
		this.basePrice = basePrice;
		this.totalFare = totalFare;
		this.jobses = jobses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extra_prices_id")
	public ExtraPrices getExtraPrices() {
		return this.extraPrices;
	}

	public void setExtraPrices(ExtraPrices extraPrices) {
		this.extraPrices = extraPrices;
	}

	@Column(name = "base_price", length = 45)
	public String getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(String basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "total_fare", length = 45)
	public String getTotalFare() {
		return this.totalFare;
	}

	public void setTotalFare(String totalFare) {
		this.totalFare = totalFare;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobFare")
	public Set<Jobs> getJobses() {
		return this.jobses;
	}

	public void setJobses(Set<Jobs> jobses) {
		this.jobses = jobses;
	}

}
